### ISSUE TITLE
Oauth

### ISSUE THREAD

**Issue by MrGekko** [reporangler/auth-service#6]
Is Oauth & jwt tokens an option for this service and its connection to the repo services?
After reading all your textual explaination I am not sure how all the services connect an what the meta data consists of. It might be an idea to create flow charts for your intended implementation.
(https://www.draw.io/)

**Comment by christhomas** [comment]
The tool (composer, npm, yarn, etc) connects to a repo service and sends whatever auth it supports to it, so the tool needs no modification. The repo service will add the repo service type to the auth data so the auth service knows from which service this is a login

The repo service then needs to know what user this is, so it'll connect to the auth service and send the recognised auth data in order to retrieve the user and package group information related to that data (no auth = public package group)

The repo service then connects to the metadata store to retrieve a list of packages that this user is allowed to access and sends that back to the tool, which processes which packages it wants to download.

The tool then starts to download files from the data given, or proxies the file requests to where the files are actually stored. Which could be a storage-service that takes care of the physical file management.

**Comment by christhomas** [comment]
As for oauth and jwt. In the case of composer, those aren't supported auth types according to the composer documentation. However we could "bend the rules" a little bit and reuse the existing types of auth to encode oauth and jwt, with a custom header then we could inside the auth service recognise this and parse the data out.

The problem is that the tools don't support it, so there is no transparent mechanism to accomplish this, you'd have to jump through some hoops in order to get that to work.

Maybe you have a proposed data flow you'd like that I can use as an example?

**Comment by MrGekko** [comment]
Ok, thanks for the explanation it clarifies your intentions.
I am by no means a Oauth expert, but it looked to me like a nice tool for inter-service & client to tool communication.

**Comment by christhomas** [comment]
I know you closed this issue, but I was thinking about this today and I think I might have a semi-transparent way for this to work without having to do so much hard work. Check it out?

https://github.com/reporangler/auth-service/issues/11
